# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rgb_strip_commands_pb2 as rgb__strip__commands__pb2


class RGBStripCommandStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TurnOn = channel.unary_unary(
                '/rgbstripcommands.RGBStripCommand/TurnOn',
                request_serializer=rgb__strip__commands__pb2.TurnOnRequest.SerializeToString,
                response_deserializer=rgb__strip__commands__pb2.TurnOnResponse.FromString,
                )


class RGBStripCommandServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TurnOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RGBStripCommandServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TurnOn': grpc.unary_unary_rpc_method_handler(
                    servicer.TurnOn,
                    request_deserializer=rgb__strip__commands__pb2.TurnOnRequest.FromString,
                    response_serializer=rgb__strip__commands__pb2.TurnOnResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rgbstripcommands.RGBStripCommand', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RGBStripCommand(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TurnOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rgbstripcommands.RGBStripCommand/TurnOn',
            rgb__strip__commands__pb2.TurnOnRequest.SerializeToString,
            rgb__strip__commands__pb2.TurnOnResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
