# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rgb_strip_commands.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rgb_strip_commands.proto',
  package='rgbstripcommands',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18rgb_strip_commands.proto\x12\x10rgbstripcommands\"4\n\rTurnOnRequest\x12#\n\x04leds\x18\x01 \x03(\x0b\x32\x15.rgbstripcommands.LED\"5\n\x0eTurnOnResponse\x12#\n\x04leds\x18\x01 \x03(\x0b\x32\x15.rgbstripcommands.LED\"<\n\x03LED\x12\x0b\n\x03num\x18\x01 \x01(\r\x12\x0b\n\x03red\x18\x02 \x01(\r\x12\r\n\x05green\x18\x03 \x01(\r\x12\x0c\n\x04\x62lue\x18\x04 \x01(\r2`\n\x0fRGBStripCommand\x12M\n\x06TurnOn\x12\x1f.rgbstripcommands.TurnOnRequest\x1a .rgbstripcommands.TurnOnResponse\"\x00\x62\x06proto3'
)




_TURNONREQUEST = _descriptor.Descriptor(
  name='TurnOnRequest',
  full_name='rgbstripcommands.TurnOnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='leds', full_name='rgbstripcommands.TurnOnRequest.leds', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=98,
)


_TURNONRESPONSE = _descriptor.Descriptor(
  name='TurnOnResponse',
  full_name='rgbstripcommands.TurnOnResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='leds', full_name='rgbstripcommands.TurnOnResponse.leds', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=153,
)


_LED = _descriptor.Descriptor(
  name='LED',
  full_name='rgbstripcommands.LED',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='rgbstripcommands.LED.num', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='red', full_name='rgbstripcommands.LED.red', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='green', full_name='rgbstripcommands.LED.green', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blue', full_name='rgbstripcommands.LED.blue', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=215,
)

_TURNONREQUEST.fields_by_name['leds'].message_type = _LED
_TURNONRESPONSE.fields_by_name['leds'].message_type = _LED
DESCRIPTOR.message_types_by_name['TurnOnRequest'] = _TURNONREQUEST
DESCRIPTOR.message_types_by_name['TurnOnResponse'] = _TURNONRESPONSE
DESCRIPTOR.message_types_by_name['LED'] = _LED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TurnOnRequest = _reflection.GeneratedProtocolMessageType('TurnOnRequest', (_message.Message,), {
  'DESCRIPTOR' : _TURNONREQUEST,
  '__module__' : 'rgb_strip_commands_pb2'
  # @@protoc_insertion_point(class_scope:rgbstripcommands.TurnOnRequest)
  })
_sym_db.RegisterMessage(TurnOnRequest)

TurnOnResponse = _reflection.GeneratedProtocolMessageType('TurnOnResponse', (_message.Message,), {
  'DESCRIPTOR' : _TURNONRESPONSE,
  '__module__' : 'rgb_strip_commands_pb2'
  # @@protoc_insertion_point(class_scope:rgbstripcommands.TurnOnResponse)
  })
_sym_db.RegisterMessage(TurnOnResponse)

LED = _reflection.GeneratedProtocolMessageType('LED', (_message.Message,), {
  'DESCRIPTOR' : _LED,
  '__module__' : 'rgb_strip_commands_pb2'
  # @@protoc_insertion_point(class_scope:rgbstripcommands.LED)
  })
_sym_db.RegisterMessage(LED)



_RGBSTRIPCOMMAND = _descriptor.ServiceDescriptor(
  name='RGBStripCommand',
  full_name='rgbstripcommands.RGBStripCommand',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=217,
  serialized_end=313,
  methods=[
  _descriptor.MethodDescriptor(
    name='TurnOn',
    full_name='rgbstripcommands.RGBStripCommand.TurnOn',
    index=0,
    containing_service=None,
    input_type=_TURNONREQUEST,
    output_type=_TURNONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RGBSTRIPCOMMAND)

DESCRIPTOR.services_by_name['RGBStripCommand'] = _RGBSTRIPCOMMAND

# @@protoc_insertion_point(module_scope)
